// <auto-generated />
namespace api.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open api.Context

[<DbContext(typeof<CustomDbContext>)>]
[<Migration("20220925094507_RestauranteModel")>]
type RestauranteModel() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        ()

    override this.Down(migrationBuilder:MigrationBuilder) =
        ()

    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "6.0.8") |> ignore

        modelBuilder.Entity("api.Models.Pizza", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                |> ignore

            b.Property<string>("Name")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Pizzas") |> ignore

        )) |> ignore

